
CREATE TABLE IF NOT EXISTS authors(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
	fname VARCHAR(255) NOT NULL,
	lname VARCHAR(255) NOT NULL,
	birth_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS books(
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
	name VARCHAR(512) NOT NULL,
	year BIGINT,
	descr VARCHAR(2048),
	rating BIGINT,
	author_id BIGINT
)

